### ISSUE TITLE
为什么使用我自己域名发现大量资源无法加载，404

### ISSUE THREAD

**Issue by xieke12** [linwoodpendleton/nginx_proxy_conf#2]
![image](https://user-images.githubusercontent.com/29595434/191179653-d0709016-2b36-4843-84a0-cc864f68c904.png)

**Comment by linwoodpendleton** [comment]
地址没有加入白名单.

**Comment by xieke12** [comment]
请问这个应该怎么改呢，是下面截图的吗？这目前是照抄的[www.php8.ltd.conf](https://github.com/linwoodpendleton/nginx_proxy_conf/blob/main/www.php8.ltd.conf)


![image](https://user-images.githubusercontent.com/29595434/191439438-12414062-9f4e-4734-a206-1383cabc54dd.png)

**Comment by xieke12** [comment]
哦。知道了。感谢up
少加了 github.githubassets.com
