### ISSUE TITLE
老哥还在维护这个吗? 能否添加下自定义端口的功能?

### ISSUE THREAD

**Issue by wutongskype** [linwoodpendleton/nginx_proxy_conf#4]
443 已经被其他Server占用了, 我设置了其他端口,但是这个配置还是会把端口跳转回443.

**Comment by linwoodpendleton** [comment]
更新了.增加特殊端口支持.
测试:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url)
测试2:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url)

**Comment by wutongskype** [comment]
> 更新了.增加特殊端口支持. 测试:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url) 测试2:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url)

![image](https://github.com/linwoodpendleton/nginx_proxy_conf/assets/40192806/648d5974-6405-42d8-8d30-cd5d0e50a67b)

测试了下, 还可以, 另外请问这里为什么有两个 HostLocMJJ ?
location /HostLocMJJ/HostLocMJJ/ {

和上面的 location /HostLocMJJ/  有什么区别吗? 如果改path这两个地方都需要更改吗?

**Comment by linwoodpendleton** [comment]
> > 更新了.增加特殊端口支持. 测试:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url) 测试2:[https://www.php8.ltd:4430/HostLocMJJ/https://github.com/](url)
> 
> ![image](https://user-images.githubusercontent.com/40192806/241374270-648d5974-6405-42d8-8d30-cd5d0e50a67b.png)
> 
> 测试了下, 还可以, 另外请问这里为什么有两个 HostLocMJJ ? location /HostLocMJJ/HostLocMJJ/ {
> 
> 和上面的 location /HostLocMJJ/ 有什么区别吗? 如果改path这两个地方都需要更改吗?

set $unopengzip 0; #对于强制开启压缩的网站开启替换 0 关, 1 开
主要是是用于反代某些开启强制压缩的网站. 上面这个设置为1, location /HostLocMJJ/HostLocMJJ/ 将启用


如果不懂,全部替换即可,不影响.
