### ISSUE TITLE
对default.conf的补充以及两个问题

### ISSUE THREAD

**Issue by nottellyou** [linwoodpendleton/nginx_proxy_conf#6]
1、之前用www.php8.ltd.conf没弄成功，到是用default.conf成功了。
对default.conf的补充：
```
location /HostLocMJJ/ {
            if ($request_uri ~* ^\/(.+)\/((http|https)://(www.)?([\w-]+(\.)?)+)(.*?)$) {
                set  $gotourl  $custom_host$7;
            }
            set $mjj  0;
            if ($banDomain = 1) {
                set $mjj 1;
            }
            if ($custom_host = '') {
                set $mjj 2;
            }
            if ($custom_host = 'pass') {
                set $mjj 2;
            }
            if ($mjj = 2) {
              set $gotourl $http_referer;
            }
            add_header 'xxxxx'  $gotourl;
            if ($banDomain = 1) {
                #return 200 "$gotourl";
                return 301 "$gotourl";
                #return 404 ;
            }
            if ($request_method = 'OPTIONS') {
```
加上这些代码后，基本上登录v2ex。com和浏览发贴都正常。也有不完善的地方，如贴子详情页分页。这个我搞不定了

问题2：如何修改代码可以支持github.com的登录和发贴呢？目前登录时会报session有问题，我也摸不着头脑。
问题3：可否支持gmail的登录呢？好久都没有上过gmail了。

最后，感谢你提供的这个好工具。

**Comment by linwoodpendleton** [comment]
以前实现过github.com和gmail登陆,不过网址会瞬间变红,会被浏览器拦截.

**Comment by nottellyou** [comment]
网址变红难道是浏览器认为钓鱼网站？

**Comment by linwoodpendleton** [comment]
是的,所以头部这几个网站是不能反代它的,特别是电商类的,比如亚马逊

**Comment by nottellyou** [comment]
请问大哥，如何修复 https://v2ex.com/t/1024274?p=3分页问题呢？网页源代码为 ```  <a href="?p=3" class="page_normal">3</a> ```
是一个相对地址，目前我只能手工拼到url上，一点击就会跑到整个分类对应的列表页。

**Comment by linwoodpendleton** [comment]
> 请问大哥，如何修复 [https://v2ex.com/t/1024274?p=3分页问题呢？网页源代码为](https://v2ex.com/t/1024274?p=3%E5%88%86%E9%A1%B5%E9%97%AE%E9%A2%98%E5%91%A2%EF%BC%9F%E7%BD%91%E9%A1%B5%E6%BA%90%E4%BB%A3%E7%A0%81%E4%B8%BA) ` <a href="?p=3" class="page_normal">3</a>` 是一个相对地址，目前我只能手工拼到url上，一点击就会跑到整个分类对应的列表页。

https://www.php8.ltd/HostLocMJJ/https://v2ex.com/t/1024274 
这个网址,我这里在并没有看到分页

**Comment by nottellyou** [comment]
抱歉，这个地址https://v2ex.com/t/613460?p=3，上面那个地址应该是我复制错了。

**Comment by linwoodpendleton** [comment]
https://www.php8.ltd/HostLocMJJ/[https://v2ex.com/t/613460?p=3

我这个正常

https://xxxxx.xx.net/HostLocMJJ/https://github.com/hex-ci/discuz-plugins/tree/master/register_limit

这个是替换错了JS 文件,报错了.等我有容研究一下.

**Comment by nottellyou** [comment]
你好，大哥，我记得以前 https://v2.xxxxx.cc/HostLocMJJ/https://v2ex.com/write  是好好的，可以发主题贴，但现在不行了。我印象中并没有改动过什么配置？

可否，看看呢？

**Comment by linwoodpendleton** [comment]
> 你好，大哥，我记得以前 https://v2.xxxxx.cc/HostLocMJJ/https://v2ex.com/write 是好好的，可以发主题贴，但现在不行了。我印象中并没有改动过什么配置？
> 
> 可否，看看呢？

https://www.php8.ltd/HostLocMJJ/https://v2ex.com/write 我的好像可以

**Comment by nottellyou** [comment]
我知道了，是浏览器版本问题，后来我为了降低内存占用换了一个低版本的浏览器，换回高版本后，正常 了。
